export const microbes_list = [
	'Acinetobacter baumannii',
	'Campylobacter spp',
	'Citrobacter spp Contaminants',
	'Enterobacter spp',
	'Enterobacteriaceae',
	'Surveil kal',
	'Esterococcus sp',
	'H Influenza',
	'Klebsiella pneumonia',
	'MRSA',
	'N. Gonorrhoea',
	'Nonfermenter GNB',
	'Normal Flora',
	'Proteus mirabilis',
	'Proteus vulgaris',
	'Providencia spp',
	'Pseudomonas aeruginosa',
	'bacilli',
	'coccob',
	'Pseudomonas spp',
	'Salmonella spp',
	'Staphylococcus aureus',
	'Staphylococcus spp',
	'Streptococcus pneumonia',
	'Streptococcus spp',
	'other',
]
export const antibiotic_list = [
	'Amikacin',
	'Amoxicillin-clavulanate',
	'Amoxycillin',
	'Ampicillin',
	'Ampicillin sulbactam',
	'Azithromycin',
	'Cefazolin',
	'Cefepime',
	'Cefotaxime',
	'Ceftazidime',
	'Ceftazidime Clavulanic Aci',
	'Ceftriaxone',
	'Cefuroxime',
	'Ciprofloxacin',
	'Clavalunic Acid',
	'Clindamycin',
	'Colistin',
	'Doxycillin',
	'Erythromycin',
	'Gentamycin',
	'Levofloxacin',
	'Linezolid',
	'Meropenem',
	'Nitrofurantoin',
	'Norfloxacin',
	'Ofloxacin',
	'Penicillin',
	'Piperacillin-Tazobactum ',
	'Tetracycline',
	'Tigecycline',
	'Trimethoprim-sulfametho:',
	'vancomycin',
	'other',
]
